Repository terraform-providers/terraform-provider-circonus, pull requests merged in 2020-01, with the labels that each got.

#37 Maintenance support
  CHANGELOG.md
  circonus/provider.go
  circonus/resource_circonus_maintenance.go
  circonus/resource_circonus_maintenance_test.go
  circonus/resource_circonus_rule_set.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/expand_json.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/flatten_json.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/normalize_json.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/suppress_json_diff.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/float.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/int.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/meta.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/network.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/strings.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/testing.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/time.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/uuid.go
  vendor/github.com/mattn/go-isatty/go.test.sh
  vendor/github.com/mattn/go-isatty/renovate.json
  vendor/golang.org/x/sys/cpu/cpu_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_arm64.s
  vendor/golang.org/x/sys/cpu/cpu_gc_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.c
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.go
  vendor/golang.org/x/sys/cpu/hwcap_linux.go
  vendor/golang.org/x/sys/unix/zptrace_armnn_linux.go
  vendor/golang.org/x/sys/unix/zptrace_linux_arm64.go
  vendor/golang.org/x/sys/unix/zptrace_mipsnn_linux.go
  vendor/golang.org/x/sys/unix/zptrace_mipsnnle_linux.go
  vendor/golang.org/x/sys/unix/zptrace_x86_linux.go
  vendor/modules.txt
  website/circonus.erb
  website/docs/r/maintenance.html.markdown
Labels: dependencies, documentation, size/XXL

#38 fix maintenance test to deal with local timezone of the test
  circonus/resource_circonus_maintenance_test.go
Labels: size/XS

#39 fix: tz for maintenance window test
  circonus/resource_circonus_maintenance_test.go
Labels: size/XS

#40 eliminate problematic time conversion code in rulesets and just stick…
  circonus/resource_circonus_rule_set.go
  circonus/resource_circonus_rule_set_test.go
Labels: size/XL
