Repository terraform-providers/terraform-provider-circonus, pull requests merged in 2020-02, with the labels that each got.

#41 add support for redis checks
  CHANGELOG.md
  circonus/check.go
  circonus/resource_circonus_check.go
  circonus/resource_circonus_check_redis.go
  circonus/resource_circonus_check_redis_test.go
  circonus/resource_circonus_maintenance_test.go
  circonus/resource_circonus_rule_set.go
  circonus/resource_circonus_rule_set_test.go
  website/docs/r/check.html.markdown
Labels: documentation, size/XL

#42 Add `dns` check, metric_filters to list
  CHANGELOG.md
  circonus/check.go
  circonus/resource_circonus_check.go
  circonus/resource_circonus_check_dns.go
  circonus/resource_circonus_check_dns_test.go
  go.mod
  main.go
  website/docs/r/check.html.markdown
Labels: documentation, size/XL

#43 state widget support in the dashboard
  CHANGELOG.md
  circonus/resource_circonus_dashboard.go
  go.mod
  go.sum
  vendor/github.com/circonus-labs/go-apiclient/dashboard.go
  vendor/modules.txt
Labels: dependencies, size/M

#44 Fix copy pasta in State widget settings
  circonus/resource_circonus_dashboard.go
Labels: size/XS

#45 doc: update period and timeout for check, string with duration
  website/docs/r/check.html.markdown
Labels: documentation, size/XS
